language: r
cache: packages
branches:
    only:
        - master
r_github_packages:
    - rstudio/blogdown


script:
    - Rscript -e 'blogdown::install_hugo()'
    - Rscript -e 'blogdown::build_site()'

deploy:
    provider: master
    skip_cleanup: true
    github_token: $GITHUB_PAT
    on:
        branch: master
    local_dir: public
    target_branch: gh-pages